import { OnshapeId } from '../onshape.types'

export interface OnshapePartStudioTranslation {
  allowFaultyParts: boolean
  angularTolerance: number
  blobElementId: OnshapeId
  blobMicroversionId: OnshapeId
  cloudObjectId: string
  cloudStorageAccountId: string
  colorMethod: string
  configuration: string
  connectionId: string
  createComposite: boolean
  currentSheetOnly: boolean
  destinationName: string
  distanceTolerance: number
  elementId: string
  elementIds: OnshapeId[]
  emailLink: boolean
  emailMessage: string
  emailSubject: string
  emailTo: string[]
  evaluateExportRule: boolean
  excludeHiddenEntities: boolean
  excludeOffSheetContent: boolean
  extractAssemblyHierarchy: boolean
  flatten: boolean
  flattenAssemblies: boolean
  foreignId: string
  formatName: string
  fromUserId: string
  getyAxisIsUp: boolean
  grouping: boolean
  hideInspectionItems: boolean
  ignoreExportRulesForContents: boolean
  imageHeight: number
  imageWidth: number
  importAppearances: boolean
  importInBackground: boolean
  importMaterialDensity: boolean
  importWithinDocument: boolean
  includeExportIds: boolean
  joinAdjacentSurfaces: boolean
  level: string
  linkDocumentId: string
  linkDocumentWorkspaceId: string
  maximumChordLength: number
  notifyUser: boolean
  occurrencesToExport: string
  onePartPerDoc: boolean
  originalForeignId: string
  parasolidMode: string
  parentId: string
  partIds: string
  partsExportFilter: {
    btType: string
    skipAllMesh: boolean
    skipCurves: boolean
    skipPartialMesh: boolean
  },
  password: string
  passwordRequired: boolean
  pdfVersion: string
  processedForeignId: string
  projectId: string
  proxyDocumentId: string
  proxyElementId: string
  proxyWorkspaceVersion: string
  proxyWorkspaceVersionId: string
  resolution: string
  rhinoVersion: string
  selectablePdfText: boolean
  sendCopyToMe: boolean
  sheetIndices: number[]
  showOverriddenDimensions: boolean
  skipBodyshop: boolean
  sourceName: string
  specifyMaterialData: boolean
  specifyUnits: boolean
  splinesAsPolylines: boolean
  splitAssembliesIntoMultipleDocuments: boolean
  stepParasolidPreprocessingOption: string
  stepVersionString: string
  stlMode: string
  storeInDocument: boolean
  textAsGeometry: boolean
  textOption: string
  triggerAutoDownload: boolean
  unit: string
  uploadId: string
  useFileNameToSetSinglePartName: boolean
  useGltfCompression: boolean
  useIGESImportPostProcessing: boolean
  useIgesCompatibilityMode: boolean
  validForDays: number
  versionString: string
}